### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by djc** [ctz/rustls-native-certs#1]
What are blockers for this? Is it just a fresh release of security-framework appearing, as well?

**Comment by ctz** [comment]
I've added some notes to https://github.com/ctz/rustls-native-certs/projects/1 of what I'm working on here

**Comment by djc** [comment]
Thanks!

**Comment by Ralith** [comment]
Re: API quality: live tracking of changes to the underlying certificate store would be very cool, but I think even the simplest one-time snapshot would still be a step up from the status quo; restarting your service is a lot less work than rebuilding it from source.

**Comment by ctz** [comment]
https://crates.io/crates/rustls-native-certs/0.1.0
