### ISSUE TITLE
Consider using non-rustls types in the API

### ISSUE THREAD

**Issue by Ralith** [ctz/rustls-native-certs#2]
In its current form, this library must be updated for every new rustls release. Given the small size and specific responsibilities, removing the rustls dependency would likely allow the library to remain unchanged for much longer periods, reducing maintenance load. As a straw proposal, DER blobs could be returned as `Vec<Vec<u8>>`.

**Comment by djc** [comment]
Plus rustls could have like a `TryFrom` impl for whatever type you use here?

**Comment by ctz** [comment]
I'll probably need to hoist the PEM code out of rustls to achieve this. But that seems like a good idea.

**Comment by Ralith** [comment]
This is currently making it difficult to have a git dependency on rustls, which causes problems like https://github.com/djc/quinn/issues/805.

**Comment by est31** [comment]
:+1: I wanted to use this crate with reqwest's rustls mode and call [add_root_certificate](https://docs.rs/reqwest/0.10.8/reqwest/struct.ClientBuilder.html#method.add_root_certificate) but reqwest has its own certificate types which abstract over the various backends, so the rustls types aren't helpful here. I guess reqwest doesn't want to become dependent on the version of rustls so it'll likely not want to expose compatibility with rustls types in the API.

**Comment by est31** [comment]
#12
