### ISSUE TITLE
Possibility to skip failed certificates instead of throwing error?

### ISSUE THREAD

**Issue by roqvist** [ctz/rustls-native-certs#5]
On my Windows machine I had a few certificates that had been added with wrong Intended Purpose flags. In the certificate store they identified themselves as capable of *All* purposes but when `load_native_certs` tried to get them as DER a panic occured.

Running the tests on my machine, with the wrong certificate flags, causes this:
```
thread 'netflix' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: 
BadDER }', src\libcore\result.rs:1165:5
```

I did not add these certificates myself and I'm not sure what software did, maybe it was my organization/company. In my case I was able to resolve this simply by unchecking the Server authentication purpose flag after locating which certificates caused the panic. The point is, at least in Windows, it appears certificates can be added with false purpose flags and having one of these in the store will put any app that depends on this crate to a halt.

I'm fine if this is the intended purpose, and I realize the error is with the certificate itself and not the crate, I just wanted to lift the question in case the crate should be more forgiving. It could  just continue iterating remaining certificates if it fails converting one, or the behavior could be controlled by some configuration/parameter to support both cases.

**Comment by Ralith** [comment]
For software that might be delivered to end users, panicking because there's a malformed file somewhere on the system that the user might not even be aware of is definitely not viable.

**Comment by ctz** [comment]
0.2.1 is published with this API change/
